[project]
name = "Landlocked!"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PySide6",
    "requests",
]

[tool.pyside6]
main_file = "src/landlocked/main.py"
